on:
  push:
    branches: main
  #Remember GitHub is on UTC time, which is 7 hours ahead of Idaho time during winter semester.
  #I think I have enough actions time to have this run every 2 hours. 
  #Turned off for now. 
  #schedule:
  #  - cron: '55 */2 * * *'

name: Render and Publish

# you need these permissions to publish to GitHub pages
# permissions: 
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: 
            any::tidyverse
            any::knitr
            any::DT

      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
